/**
 * Platform data for /dev/connect sub-routes.
 * Each entry defines a supported MCP client or integration method
 * with its configuration snippets, deep-links, and metadata.
 */

export interface PlatformConfig {
  id: string;
  name: string;
  shortName: string;
  slug: string;
  icon: string; // emoji or short label for fallback
  color: string; // tailwind color class
  bgGradient: string;
  tagline: string;
  description: string;
  docsUrl: string;
  transport: ('stdio' | 'http' | 'sse')[];
  configType: 'json' | 'cli' | 'ui' | 'python' | 'api';
  category: 'ide' | 'chat' | 'api' | 'framework' | 'runtime' | 'registry';
}

export const PLATFORMS: PlatformConfig[] = [
  {
    id: 'claude-desktop',
    name: 'Claude Desktop & Claude Code',
    shortName: 'Claude',
    slug: 'claude',
    icon: '🟤',
    color: 'orange',
    bgGradient: 'from-orange-50 to-amber-50',
    tagline: 'The primary MCP ecosystem',
    description: 'Connect via claude_desktop_config.json, .mcp.json, or the claude CLI.',
    docsUrl: 'https://docs.anthropic.com/en/docs/agents-and-tools/mcp',
    transport: ['stdio', 'http'],
    configType: 'json',
    category: 'ide',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    shortName: 'Cursor',
    slug: 'cursor',
    icon: '⚡',
    color: 'blue',
    bgGradient: 'from-blue-50 to-indigo-50',
    tagline: 'AI-first code editor',
    description: 'Add to .cursor/mcp.json — same format you already know.',
    docsUrl: 'https://cursor.com/docs/context/mcp',
    transport: ['stdio', 'http', 'sse'],
    configType: 'json',
    category: 'ide',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    shortName: 'Windsurf',
    slug: 'windsurf',
    icon: '🏄',
    color: 'teal',
    bgGradient: 'from-teal-50 to-cyan-50',
    tagline: 'Codeium\'s agentic IDE',
    description: 'Configure in mcp_config.json with serverUrl for remote MCP.',
    docsUrl: 'https://docs.windsurf.com/windsurf/cascade/mcp',
    transport: ['stdio', 'http', 'sse'],
    configType: 'json',
    category: 'ide',
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    shortName: 'ChatGPT',
    slug: 'chatgpt',
    icon: '💬',
    color: 'green',
    bgGradient: 'from-green-50 to-emerald-50',
    tagline: 'Full MCP in Developer Mode',
    description: 'Add as a Connector in ChatGPT settings — no code needed.',
    docsUrl: 'https://help.openai.com/en/articles/12584461-developer-mode-apps-and-full-mcp-connectors-in-chatgpt-beta',
    transport: ['http', 'sse'],
    configType: 'ui',
    category: 'chat',
  },
  {
    id: 'openai-agents-sdk',
    name: 'OpenAI Agents SDK',
    shortName: 'Agents SDK',
    slug: 'openai-agents',
    icon: '🤖',
    color: 'slate',
    bgGradient: 'from-slate-50 to-gray-100',
    tagline: 'Build agents with MCP tools',
    description: 'Use MCPServerStreamableHttp to connect your Python agents.',
    docsUrl: 'https://openai.github.io/openai-agents-python/mcp/',
    transport: ['stdio', 'http'],
    configType: 'python',
    category: 'api',
  },
  {
    id: 'openai-responses-api',
    name: 'OpenAI Responses API',
    shortName: 'Responses API',
    slug: 'openai-responses',
    icon: '🔌',
    color: 'gray',
    bgGradient: 'from-gray-50 to-slate-100',
    tagline: 'MCP as a first-class tool type',
    description: 'Pass type: "mcp" in the tools array — zero infrastructure.',
    docsUrl: 'https://platform.openai.com/docs/guides/tools-remote-mcp',
    transport: ['http', 'sse'],
    configType: 'api',
    category: 'api',
  },
  {
    id: 'gemini',
    name: 'Gemini CLI',
    shortName: 'Gemini',
    slug: 'gemini',
    icon: '♊',
    color: 'blue',
    bgGradient: 'from-blue-50 to-sky-50',
    tagline: 'Google\'s CLI with MCP support',
    description: 'Configure in ~/.gemini/settings.json for Gemini CLI.',
    docsUrl: 'https://geminicli.com/docs/tools/mcp-server/',
    transport: ['stdio', 'http'],
    configType: 'json',
    category: 'ide',
  },
  {
    id: 'android-studio',
    name: 'Android Studio (Gemini)',
    shortName: 'Android Studio',
    slug: 'android-studio',
    icon: '📱',
    color: 'green',
    bgGradient: 'from-green-50 to-lime-50',
    tagline: 'MCP in Gemini for Android devs',
    description: 'Enable in Settings → AI → MCP Servers for Agent Mode.',
    docsUrl: 'https://developer.android.com/studio/gemini/add-mcp-server',
    transport: ['stdio'],
    configType: 'json',
    category: 'ide',
  },
  {
    id: 'clawhub',
    name: 'ClawHub (OpenClaw)',
    shortName: 'ClawHub',
    slug: 'clawhub',
    icon: '🦞',
    color: 'rose',
    bgGradient: 'from-rose-50 to-pink-50',
    tagline: 'One-command install via OpenClaw',
    description: 'Install as an OpenClaw skill: clawhub install humanpages.',
    docsUrl: 'https://clawhub.com/skills/humanpages',
    transport: ['stdio'],
    configType: 'cli',
    category: 'framework',
  },
  {
    id: 'langchain',
    name: 'LangChain & LlamaIndex',
    shortName: 'LangChain',
    slug: 'langchain',
    icon: '🔗',
    color: 'purple',
    bgGradient: 'from-purple-50 to-violet-50',
    tagline: 'Framework-level MCP integration',
    description: 'Use langchain-mcp-adapters or llama-index-tools-mcp.',
    docsUrl: 'https://python.langchain.com/docs/integrations/tools/mcp/',
    transport: ['stdio', 'http'],
    configType: 'python',
    category: 'framework',
  },
  // ── Agent Runtimes ─────────────────────────────────────────
  {
    id: 'nanoclaw',
    name: 'NanoClaw',
    shortName: 'NanoClaw',
    slug: 'nanoclaw',
    icon: '🐳',
    color: 'indigo',
    bgGradient: 'from-indigo-50 to-blue-50',
    tagline: 'Secure containerized agents',
    description: 'Docker-sandboxed agents on Anthropic\'s Agent SDK. WhatsApp, Telegram, Slack.',
    docsUrl: 'https://github.com/qwibitai/nanoclaw',
    transport: ['stdio'],
    configType: 'cli',
    category: 'runtime',
  },
  {
    id: 'zeroclaw',
    name: 'ZeroClaw',
    shortName: 'ZeroClaw',
    slug: 'zeroclaw',
    icon: '🦀',
    color: 'orange',
    bgGradient: 'from-orange-50 to-red-50',
    tagline: 'Rust-based, 3 MB, edge-ready',
    description: 'Ultra-lightweight Rust runtime — runs on Raspberry Pi and $10 hardware.',
    docsUrl: 'https://github.com/zeroclaw-labs/zeroclaw',
    transport: ['stdio', 'sse'],
    configType: 'json',
    category: 'runtime',
  },
  {
    id: 'nanobot',
    name: 'Nanobot',
    shortName: 'Nanobot',
    slug: 'nanobot',
    icon: '🐈',
    color: 'cyan',
    bgGradient: 'from-cyan-50 to-teal-50',
    tagline: 'MCP servers → full agents',
    description: 'Open-source framework that wraps MCP servers with reasoning, memory, and UI.',
    docsUrl: 'https://github.com/nanobot-ai/nanobot',
    transport: ['stdio', 'sse'],
    configType: 'json',
    category: 'runtime',
  },
  {
    id: 'trustclaw',
    name: 'TrustClaw',
    shortName: 'TrustClaw',
    slug: 'trustclaw',
    icon: '🛡️',
    color: 'emerald',
    bgGradient: 'from-emerald-50 to-green-50',
    tagline: 'Cloud-sandboxed execution',
    description: 'Managed cloud agent sandbox — zero local setup, zero local risk.',
    docsUrl: 'https://trustclaw.com',
    transport: ['sse'],
    configType: 'ui',
    category: 'runtime',
  },
  {
    id: 'picoclaw',
    name: 'PicoClaw',
    shortName: 'PicoClaw',
    slug: 'picoclaw',
    icon: '🤏',
    color: 'yellow',
    bgGradient: 'from-yellow-50 to-amber-50',
    tagline: 'IoT & edge — 10 MB RAM',
    description: 'Ultra-lightweight Go agent for IoT devices, Raspberry Pi, and embedded systems.',
    docsUrl: 'https://github.com/sipeed/picoclaw',
    transport: ['stdio', 'sse'],
    configType: 'json',
    category: 'runtime',
  },
  {
    id: 'maxclaw',
    name: 'MaxClaw',
    shortName: 'MaxClaw',
    slug: 'maxclaw',
    icon: '🚀',
    color: 'violet',
    bgGradient: 'from-violet-50 to-purple-50',
    tagline: 'MiniMax cloud — deploy in 10s',
    description: 'Fully managed cloud agent by MiniMax. No setup, always-on, free credits.',
    docsUrl: 'https://maxclaw.ai',
    transport: ['sse'],
    configType: 'ui',
    category: 'runtime',
  },
  // ── Registries ────────────────────────────────────────────
  {
    id: 'smithery',
    name: 'Smithery',
    shortName: 'Smithery',
    slug: 'smithery',
    icon: '🔨',
    color: 'sky',
    bgGradient: 'from-sky-50 to-blue-50',
    tagline: 'Largest MCP server registry',
    description: 'CLI that auto-configures any MCP client. One command to install.',
    docsUrl: 'https://smithery.ai',
    transport: ['stdio', 'http', 'sse'],
    configType: 'cli',
    category: 'registry',
  },
];

export const MCP_SERVER_URL = 'https://mcp.humanpages.ai/sse';
export const MCP_NPX_COMMAND = 'npx -y humanpages';
export const API_BASE_URL = 'https://humanpages.ai';

/** Group platforms by category for the overview page */
export function getPlatformsByCategory() {
  const categories = {
    ide: { label: 'IDEs & Code Editors', platforms: [] as PlatformConfig[] },
    chat: { label: 'Chat Interfaces', platforms: [] as PlatformConfig[] },
    api: { label: 'APIs & SDKs', platforms: [] as PlatformConfig[] },
    runtime: { label: 'Agent Runtimes', platforms: [] as PlatformConfig[] },
    framework: { label: 'Frameworks & Libraries', platforms: [] as PlatformConfig[] },
    registry: { label: 'Registries & Directories', platforms: [] as PlatformConfig[] },
  };
  for (const p of PLATFORMS) {
    categories[p.category].platforms.push(p);
  }
  return categories;
}
