// ─── Onboarding Wizard Constants ───

export const STORAGE_KEY = 'hp_onboarding_draft';

export const STEP_LABELS = ['Notifications', 'Connect', 'CV Upload', 'Skills', 'About You', 'Availability', 'Services', 'Verification'] as const;

export const PROFICIENCY_LEVELS = [
  'Native',
  'Fluent',
  'Advanced',
  'Conversational',
  'Basic',
];

export const COMMON_LANGUAGES = [
  'English', 'Spanish', 'Mandarin', 'French', 'German', 'Portuguese', 'Japanese',
  'Hindi', 'Arabic', 'Russian', 'Korean', 'Italian', 'Dutch', 'Turkish', 'Polish',
  'Swedish', 'Hebrew', 'Thai', 'Vietnamese', 'Indonesian', 'Czech', 'Greek',
  'Romanian', 'Hungarian', 'Danish', 'Finnish', 'Norwegian', 'Ukrainian', 'Bengali',
  'Urdu', 'Malay', 'Tagalog', 'Swahili', 'Persian', 'Tamil', 'Telugu',
];

export const SKILL_CATEGORIES: Record<string, string[]> = {
  'Marketing & Sales': ['Social Media Management', 'SEO & SEM', 'Email Marketing', 'Sales & Lead Generation', 'Cold Outreach', 'Market Research', 'Influencer Marketing', 'Affiliate Marketing', 'Brand Strategy', 'Public Relations', 'Growth Hacking'],
  'Content & Writing': ['Content Writing', 'Copywriting', 'Proofreading & Editing', 'Technical Writing', 'Blog Writing', 'Ghostwriting', 'Grant Writing', 'Resume & Cover Letters', 'Script Writing'],
  'Design & Creative': ['Graphic Design', 'UI/UX Design', 'Photo & Image Editing', 'Video Production', 'Video Editing', 'Prototyping & Wireframing', 'Logo Design', 'Illustration', 'Animation & Motion Graphics', 'Brand Identity', '3D Modeling'],
  'Development & Tech': ['Software Development', 'Web Development', 'Mobile App Development', 'QA & Bug Testing', 'Code Review', 'DevOps & Cloud', 'Database Management', 'API Development', 'WordPress & CMS', 'AI & Machine Learning'],
  'Admin & Support': ['Virtual Assistant', 'Customer Support', 'Chat & Email Support', 'Data Entry', 'Email & Calendar Management', 'Scheduling', 'Document Management', 'Bookkeeping', 'Project Management', 'CRM Management'],
  'Education & Tutoring': ['English Teaching', 'Language Tutoring', 'Math Tutoring', 'Science Tutoring', 'Music Lessons', 'Test Prep & SAT', 'Academic Writing Help', 'Online Course Creation', 'Mentoring'],
  'Translation & Language': ['Translation', 'Interpretation', 'Localization', 'Subtitling & Captions', 'Transcription', 'Voiceover'],
  'Travel & Hospitality': ['Travel Planning', 'Tour Guide', 'Local Guide', 'Event Coordination', 'Concierge Services', 'Hotel & Airbnb Management'],
  'Transportation & Delivery': ['Personal Driver', 'Package Delivery', 'Courier Services', 'Airport Transfers', 'Moving & Relocation', 'Errand Running'],
  'Home & Personal Services': ['Pet Care', 'Dog Walking', 'House Sitting', 'Babysitting', 'Elder Care', 'Personal Shopping', 'Cooking & Meal Prep', 'Cleaning', 'Furniture Assembly', 'Handyman', 'Gardening & Landscaping'],
  'Community & Social': ['Community Management', 'Social Media Moderation', 'Discord & Telegram Management', 'Forum Moderation', 'Event Planning', 'Fundraising'],
  'Professional Services': ['Legal Research', 'Tax Preparation', 'Financial Consulting', 'Business Consulting', 'Real Estate', 'Insurance', 'Document Notarization', 'HR & Recruiting'],
  'Local & In-Person': ['Local Photography', 'In-Person Verification', 'Mystery Shopping', 'Survey & Feedback', 'In-Home Tech Support', 'Fitness Training', 'Tailoring & Alterations', 'Auto Repair'],
};

export const POPULAR_SKILLS = ['Virtual Assistant', 'Content Writing', 'Graphic Design', 'Social Media Management', 'English Teaching', 'Translation', 'Video Editing', 'Web Development', 'Data Entry', 'Customer Support', 'Tour Guide', 'Personal Driver', 'SEO', 'Testing', 'Localization'];
export const SKILL_SUGGESTIONS = Object.values(SKILL_CATEGORIES).flat();
// Hierarchical service categories with subcategories and title suggestions
export const SERVICE_CATEGORY_HIERARCHY: Record<string, { subcategories: string[]; suggestions: string[] }> = {
  'Photography': {
    subcategories: ['Portrait', 'Product', 'Event', 'Real Estate', 'Other'],
    suggestions: ['Wedding Photography', 'Product Photography', 'Portrait Photography', 'Real Estate Photography', 'Event Photography'],
  },
  'Delivery': {
    subcategories: ['Same-Day', 'Food', 'Package', 'Document', 'Other'],
    suggestions: ['Same-Day Delivery', 'Food Delivery', 'Package Delivery', 'Document Courier', 'Parcel Delivery'],
  },
  'Translation': {
    subcategories: ['Document', 'Website', 'Audio', 'Written', 'Other'],
    suggestions: ['Document Translation', 'Website Translation', 'Subtitle Translation', 'Business Document Translation', 'Technical Translation'],
  },
  'Writing': {
    subcategories: ['Content', 'Copy', 'Technical', 'Editing', 'Other'],
    suggestions: ['Blog Post Writing', 'Copywriting', 'Technical Writing', 'Content Writing', 'Proofreading & Editing'],
  },
  'Web Development': {
    subcategories: ['Frontend', 'Backend', 'Full Stack', 'WordPress', 'Other'],
    suggestions: ['Website Development', 'Custom Web Design', 'WordPress Development', 'E-commerce Development', 'Web App Development'],
  },
  'Data Entry': {
    subcategories: ['Spreadsheet', 'Database', 'Form Processing', 'Research', 'Other'],
    suggestions: ['Data Entry', 'Spreadsheet Management', 'Database Entry', 'Form Processing', 'Data Research'],
  },
  'Graphic Design': {
    subcategories: ['Logo', 'Branding', 'UI/UX', 'Social Media', 'Other'],
    suggestions: ['Logo Design', 'Graphic Design', 'Branding Design', 'Social Media Graphics', 'UI/UX Design'],
  },
  'Virtual Assistant': {
    subcategories: ['Administrative', 'Email', 'Scheduling', 'Research', 'Other'],
    suggestions: ['Virtual Assistant', 'Email Management', 'Schedule Management', 'Data Research Assistant', 'Administrative Support'],
  },
  'Tutoring': {
    subcategories: ['Language', 'Academic', 'Test Prep', 'Music', 'Other'],
    suggestions: ['English Tutoring', 'Math Tutoring', 'Language Tutoring', 'Test Prep Tutoring', 'Music Lessons'],
  },
  'Other': {
    subcategories: [],
    suggestions: [],
  },
};

export const POPULAR_SERVICE_CATEGORIES = Object.keys(SERVICE_CATEGORY_HIERARCHY);

export const COUNTRY_CODES = [
  { code: '+93', country: 'AF', flag: '🇦🇫', label: 'Afghanistan (+93)' },
  { code: '+358', country: 'AX', flag: '🇦🇽', label: 'Aland Islands (+358)' },
  { code: '+355', country: 'AL', flag: '🇦🇱', label: 'Albania (+355)' },
  { code: '+213', country: 'DZ', flag: '🇩🇿', label: 'Algeria (+213)' },
  { code: '+1', country: 'AS', flag: '🇦🇸', label: 'American Samoa (+1)' },
  { code: '+376', country: 'AD', flag: '🇦🇩', label: 'Andorra (+376)' },
  { code: '+244', country: 'AO', flag: '🇦🇴', label: 'Angola (+244)' },
  { code: '+1', country: 'AI', flag: '🇦🇮', label: 'Anguilla (+1)' },
  { code: '+672', country: 'AQ', flag: '🇦🇶', label: 'Antarctica (+672)' },
  { code: '+1', country: 'AG', flag: '🇦🇬', label: 'Antigua and Barbuda (+1)' },
  { code: '+54', country: 'AR', flag: '🇦🇷', label: 'Argentina (+54)' },
  { code: '+374', country: 'AM', flag: '🇦🇲', label: 'Armenia (+374)' },
  { code: '+297', country: 'AW', flag: '🇦🇼', label: 'Aruba (+297)' },
  { code: '+61', country: 'AU', flag: '🇦🇺', label: 'Australia (+61)' },
  { code: '+43', country: 'AT', flag: '🇦🇹', label: 'Austria (+43)' },
  { code: '+994', country: 'AZ', flag: '🇦🇿', label: 'Azerbaijan (+994)' },
  { code: '+1', country: 'BS', flag: '🇧🇸', label: 'Bahamas (+1)' },
  { code: '+973', country: 'BH', flag: '🇧🇭', label: 'Bahrain (+973)' },
  { code: '+880', country: 'BD', flag: '🇧🇩', label: 'Bangladesh (+880)' },
  { code: '+1', country: 'BB', flag: '🇧🇧', label: 'Barbados (+1)' },
  { code: '+375', country: 'BY', flag: '🇧🇾', label: 'Belarus (+375)' },
  { code: '+32', country: 'BE', flag: '🇧🇪', label: 'Belgium (+32)' },
  { code: '+501', country: 'BZ', flag: '🇧🇿', label: 'Belize (+501)' },
  { code: '+229', country: 'BJ', flag: '🇧🇯', label: 'Benin (+229)' },
  { code: '+1', country: 'BM', flag: '🇧🇲', label: 'Bermuda (+1)' },
  { code: '+975', country: 'BT', flag: '🇧🇹', label: 'Bhutan (+975)' },
  { code: '+591', country: 'BO', flag: '🇧🇴', label: 'Bolivia (+591)' },
  { code: '+387', country: 'BA', flag: '🇧🇦', label: 'Bosnia and Herzegovina (+387)' },
  { code: '+267', country: 'BW', flag: '🇧🇼', label: 'Botswana (+267)' },
  { code: '+55', country: 'BR', flag: '🇧🇷', label: 'Brazil (+55)' },
  { code: '+246', country: 'IO', flag: '🇮🇴', label: 'British Indian Ocean Territory (+246)' },
  { code: '+1', country: 'VG', flag: '🇻🇬', label: 'British Virgin Islands (+1)' },
  { code: '+673', country: 'BN', flag: '🇧🇳', label: 'Brunei (+673)' },
  { code: '+359', country: 'BG', flag: '🇧🇬', label: 'Bulgaria (+359)' },
  { code: '+226', country: 'BF', flag: '🇧🇫', label: 'Burkina Faso (+226)' },
  { code: '+257', country: 'BI', flag: '🇧🇮', label: 'Burundi (+257)' },
  { code: '+855', country: 'KH', flag: '🇰🇭', label: 'Cambodia (+855)' },
  { code: '+237', country: 'CM', flag: '🇨🇲', label: 'Cameroon (+237)' },
  { code: '+1', country: 'CA', flag: '🇨🇦', label: 'Canada (+1)' },
  { code: '+238', country: 'CV', flag: '🇨🇻', label: 'Cape Verde (+238)' },
  { code: '+1', country: 'KY', flag: '🇰🇾', label: 'Cayman Islands (+1)' },
  { code: '+236', country: 'CF', flag: '🇨🇫', label: 'Central African Republic (+236)' },
  { code: '+235', country: 'TD', flag: '🇹🇩', label: 'Chad (+235)' },
  { code: '+56', country: 'CL', flag: '🇨🇱', label: 'Chile (+56)' },
  { code: '+86', country: 'CN', flag: '🇨🇳', label: 'China (+86)' },
  { code: '+61', country: 'CX', flag: '🇨🇽', label: 'Christmas Island (+61)' },
  { code: '+61', country: 'CC', flag: '🇨🇨', label: 'Cocos Islands (+61)' },
  { code: '+57', country: 'CO', flag: '🇨🇴', label: 'Colombia (+57)' },
  { code: '+269', country: 'KM', flag: '🇰🇲', label: 'Comoros (+269)' },
  { code: '+242', country: 'CG', flag: '🇨🇬', label: 'Congo (+242)' },
  { code: '+243', country: 'CD', flag: '🇨🇩', label: 'Congo (Democratic Republic) (+243)' },
  { code: '+682', country: 'CK', flag: '🇨🇰', label: 'Cook Islands (+682)' },
  { code: '+506', country: 'CR', flag: '🇨🇷', label: 'Costa Rica (+506)' },
  { code: '+385', country: 'HR', flag: '🇭🇷', label: 'Croatia (+385)' },
  { code: '+53', country: 'CU', flag: '🇨🇺', label: 'Cuba (+53)' },
  { code: '+357', country: 'CY', flag: '🇨🇾', label: 'Cyprus (+357)' },
  { code: '+420', country: 'CZ', flag: '🇨🇿', label: 'Czech Republic (+420)' },
  { code: '+45', country: 'DK', flag: '🇩🇰', label: 'Denmark (+45)' },
  { code: '+246', country: 'DG', flag: '🇩🇬', label: 'Diego Garcia (+246)' },
  { code: '+253', country: 'DJ', flag: '🇩🇯', label: 'Djibouti (+253)' },
  { code: '+1', country: 'DM', flag: '🇩🇲', label: 'Dominica (+1)' },
  { code: '+1', country: 'DO', flag: '🇩🇴', label: 'Dominican Republic (+1)' },
  { code: '+670', country: 'TL', flag: '🇹🇱', label: 'East Timor (+670)' },
  { code: '+593', country: 'EC', flag: '🇪🇨', label: 'Ecuador (+593)' },
  { code: '+20', country: 'EG', flag: '🇪🇬', label: 'Egypt (+20)' },
  { code: '+503', country: 'SV', flag: '🇸🇻', label: 'El Salvador (+503)' },
  { code: '+240', country: 'GQ', flag: '🇬🇶', label: 'Equatorial Guinea (+240)' },
  { code: '+291', country: 'ER', flag: '🇪🇷', label: 'Eritrea (+291)' },
  { code: '+372', country: 'EE', flag: '🇪🇪', label: 'Estonia (+372)' },
  { code: '+251', country: 'ET', flag: '🇪🇹', label: 'Ethiopia (+251)' },
  { code: '+500', country: 'FK', flag: '🇫🇰', label: 'Falkland Islands (+500)' },
  { code: '+298', country: 'FO', flag: '🇫🇴', label: 'Faroe Islands (+298)' },
  { code: '+679', country: 'FJ', flag: '🇫🇯', label: 'Fiji (+679)' },
  { code: '+358', country: 'FI', flag: '🇫🇮', label: 'Finland (+358)' },
  { code: '+33', country: 'FR', flag: '🇫🇷', label: 'France (+33)' },
  { code: '+594', country: 'GF', flag: '🇬🇫', label: 'French Guiana (+594)' },
  { code: '+689', country: 'PF', flag: '🇵🇫', label: 'French Polynesia (+689)' },
  { code: '+241', country: 'GA', flag: '🇬🇦', label: 'Gabon (+241)' },
  { code: '+220', country: 'GM', flag: '🇬🇲', label: 'Gambia (+220)' },
  { code: '+995', country: 'GE', flag: '🇬🇪', label: 'Georgia (+995)' },
  { code: '+49', country: 'DE', flag: '🇩🇪', label: 'Germany (+49)' },
  { code: '+233', country: 'GH', flag: '🇬🇭', label: 'Ghana (+233)' },
  { code: '+350', country: 'GI', flag: '🇬🇮', label: 'Gibraltar (+350)' },
  { code: '+30', country: 'GR', flag: '🇬🇷', label: 'Greece (+30)' },
  { code: '+299', country: 'GL', flag: '🇬🇱', label: 'Greenland (+299)' },
  { code: '+1', country: 'GD', flag: '🇬🇩', label: 'Grenada (+1)' },
  { code: '+590', country: 'GP', flag: '🇬🇵', label: 'Guadeloupe (+590)' },
  { code: '+1', country: 'GU', flag: '🇬🇺', label: 'Guam (+1)' },
  { code: '+502', country: 'GT', flag: '🇬🇹', label: 'Guatemala (+502)' },
  { code: '+44', country: 'GG', flag: '🇬🇬', label: 'Guernsey (+44)' },
  { code: '+224', country: 'GN', flag: '🇬🇳', label: 'Guinea (+224)' },
  { code: '+245', country: 'GW', flag: '🇬🇼', label: 'Guinea-Bissau (+245)' },
  { code: '+592', country: 'GY', flag: '🇬🇾', label: 'Guyana (+592)' },
  { code: '+509', country: 'HT', flag: '🇭🇹', label: 'Haiti (+509)' },
  { code: '+379', country: 'VA', flag: '🇻🇦', label: 'Vatican (+379)' },
  { code: '+504', country: 'HN', flag: '🇭🇳', label: 'Honduras (+504)' },
  { code: '+852', country: 'HK', flag: '🇭🇰', label: 'Hong Kong (+852)' },
  { code: '+36', country: 'HU', flag: '🇭🇺', label: 'Hungary (+36)' },
  { code: '+354', country: 'IS', flag: '🇮🇸', label: 'Iceland (+354)' },
  { code: '+91', country: 'IN', flag: '🇮🇳', label: 'India (+91)' },
  { code: '+62', country: 'ID', flag: '🇮🇩', label: 'Indonesia (+62)' },
  { code: '+98', country: 'IR', flag: '🇮🇷', label: 'Iran (+98)' },
  { code: '+964', country: 'IQ', flag: '🇮🇶', label: 'Iraq (+964)' },
  { code: '+353', country: 'IE', flag: '🇮🇪', label: 'Ireland (+353)' },
  { code: '+44', country: 'IM', flag: '🇮🇲', label: 'Isle of Man (+44)' },
  { code: '+972', country: 'IL', flag: '🇮🇱', label: 'Israel (+972)' },
  { code: '+39', country: 'IT', flag: '🇮🇹', label: 'Italy (+39)' },
  { code: '+225', country: 'CI', flag: '🇨🇮', label: 'Ivory Coast (+225)' },
  { code: '+1', country: 'JM', flag: '🇯🇲', label: 'Jamaica (+1)' },
  { code: '+81', country: 'JP', flag: '🇯🇵', label: 'Japan (+81)' },
  { code: '+44', country: 'JE', flag: '🇯🇪', label: 'Jersey (+44)' },
  { code: '+962', country: 'JO', flag: '🇯🇴', label: 'Jordan (+962)' },
  { code: '+7', country: 'KZ', flag: '🇰🇿', label: 'Kazakhstan (+7)' },
  { code: '+254', country: 'KE', flag: '🇰🇪', label: 'Kenya (+254)' },
  { code: '+686', country: 'KI', flag: '🇰🇮', label: 'Kiribati (+686)' },
  { code: '+850', country: 'KP', flag: '🇰🇵', label: 'North Korea (+850)' },
  { code: '+82', country: 'KR', flag: '🇰🇷', label: 'South Korea (+82)' },
  { code: '+965', country: 'KW', flag: '🇰🇼', label: 'Kuwait (+965)' },
  { code: '+996', country: 'KG', flag: '🇰🇬', label: 'Kyrgyzstan (+996)' },
  { code: '+856', country: 'LA', flag: '🇱🇦', label: 'Laos (+856)' },
  { code: '+371', country: 'LV', flag: '🇱🇻', label: 'Latvia (+371)' },
  { code: '+961', country: 'LB', flag: '🇱🇧', label: 'Lebanon (+961)' },
  { code: '+266', country: 'LS', flag: '🇱🇸', label: 'Lesotho (+266)' },
  { code: '+231', country: 'LR', flag: '🇱🇷', label: 'Liberia (+231)' },
  { code: '+218', country: 'LY', flag: '🇱🇾', label: 'Libya (+218)' },
  { code: '+423', country: 'LI', flag: '🇱🇮', label: 'Liechtenstein (+423)' },
  { code: '+370', country: 'LT', flag: '🇱🇹', label: 'Lithuania (+370)' },
  { code: '+352', country: 'LU', flag: '🇱🇺', label: 'Luxembourg (+352)' },
  { code: '+853', country: 'MO', flag: '🇲🇴', label: 'Macau (+853)' },
  { code: '+389', country: 'MK', flag: '🇲🇰', label: 'Macedonia (+389)' },
  { code: '+261', country: 'MG', flag: '🇲🇬', label: 'Madagascar (+261)' },
  { code: '+265', country: 'MW', flag: '🇲🇼', label: 'Malawi (+265)' },
  { code: '+60', country: 'MY', flag: '🇲🇾', label: 'Malaysia (+60)' },
  { code: '+960', country: 'MV', flag: '🇲🇻', label: 'Maldives (+960)' },
  { code: '+223', country: 'ML', flag: '🇲🇱', label: 'Mali (+223)' },
  { code: '+356', country: 'MT', flag: '🇲🇹', label: 'Malta (+356)' },
  { code: '+692', country: 'MH', flag: '🇲🇭', label: 'Marshall Islands (+692)' },
  { code: '+596', country: 'MQ', flag: '🇲🇶', label: 'Martinique (+596)' },
  { code: '+222', country: 'MR', flag: '🇲🇷', label: 'Mauritania (+222)' },
  { code: '+230', country: 'MU', flag: '🇲🇺', label: 'Mauritius (+230)' },
  { code: '+262', country: 'YT', flag: '🇾🇹', label: 'Mayotte (+262)' },
  { code: '+52', country: 'MX', flag: '🇲🇽', label: 'Mexico (+52)' },
  { code: '+691', country: 'FM', flag: '🇫🇲', label: 'Micronesia (+691)' },
  { code: '+373', country: 'MD', flag: '🇲🇩', label: 'Moldova (+373)' },
  { code: '+377', country: 'MC', flag: '🇲🇨', label: 'Monaco (+377)' },
  { code: '+976', country: 'MN', flag: '🇲🇳', label: 'Mongolia (+976)' },
  { code: '+382', country: 'ME', flag: '🇲🇪', label: 'Montenegro (+382)' },
  { code: '+212', country: 'MA', flag: '🇲🇦', label: 'Morocco (+212)' },
  { code: '+258', country: 'MZ', flag: '🇲🇿', label: 'Mozambique (+258)' },
  { code: '+95', country: 'MM', flag: '🇲🇲', label: 'Myanmar (+95)' },
  { code: '+264', country: 'NA', flag: '🇳🇦', label: 'Namibia (+264)' },
  { code: '+674', country: 'NR', flag: '🇳🇷', label: 'Nauru (+674)' },
  { code: '+977', country: 'NP', flag: '🇳🇵', label: 'Nepal (+977)' },
  { code: '+31', country: 'NL', flag: '🇳🇱', label: 'Netherlands (+31)' },
  { code: '+687', country: 'NC', flag: '🇳🇨', label: 'New Caledonia (+687)' },
  { code: '+64', country: 'NZ', flag: '🇳🇿', label: 'New Zealand (+64)' },
  { code: '+505', country: 'NI', flag: '🇳🇮', label: 'Nicaragua (+505)' },
  { code: '+227', country: 'NE', flag: '🇳🇪', label: 'Niger (+227)' },
  { code: '+234', country: 'NG', flag: '🇳🇬', label: 'Nigeria (+234)' },
  { code: '+683', country: 'NU', flag: '🇳🇺', label: 'Niue (+683)' },
  { code: '+672', country: 'NF', flag: '🇳🇫', label: 'Norfolk Island (+672)' },
  { code: '+1', country: 'MP', flag: '🇲🇵', label: 'Northern Mariana Islands (+1)' },
  { code: '+47', country: 'NO', flag: '🇳🇴', label: 'Norway (+47)' },
  { code: '+968', country: 'OM', flag: '🇴🇲', label: 'Oman (+968)' },
  { code: '+92', country: 'PK', flag: '🇵🇰', label: 'Pakistan (+92)' },
  { code: '+680', country: 'PW', flag: '🇵🇼', label: 'Palau (+680)' },
  { code: '+507', country: 'PA', flag: '🇵🇦', label: 'Panama (+507)' },
  { code: '+675', country: 'PG', flag: '🇵🇬', label: 'Papua New Guinea (+675)' },
  { code: '+595', country: 'PY', flag: '🇵🇾', label: 'Paraguay (+595)' },
  { code: '+51', country: 'PE', flag: '🇵🇪', label: 'Peru (+51)' },
  { code: '+63', country: 'PH', flag: '🇵🇭', label: 'Philippines (+63)' },
  { code: '+64', country: 'PN', flag: '🇵🇳', label: 'Pitcairn Islands (+64)' },
  { code: '+48', country: 'PL', flag: '🇵🇱', label: 'Poland (+48)' },
  { code: '+351', country: 'PT', flag: '🇵🇹', label: 'Portugal (+351)' },
  { code: '+1', country: 'PR', flag: '🇵🇷', label: 'Puerto Rico (+1)' },
  { code: '+974', country: 'QA', flag: '🇶🇦', label: 'Qatar (+974)' },
  { code: '+262', country: 'RE', flag: '🇷🇪', label: 'Reunion (+262)' },
  { code: '+40', country: 'RO', flag: '🇷🇴', label: 'Romania (+40)' },
  { code: '+7', country: 'RU', flag: '🇷🇺', label: 'Russia (+7)' },
  { code: '+250', country: 'RW', flag: '🇷🇼', label: 'Rwanda (+250)' },
  { code: '+290', country: 'SH', flag: '🇸🇭', label: 'Saint Helena (+290)' },
  { code: '+1', country: 'KN', flag: '🇰🇳', label: 'Saint Kitts and Nevis (+1)' },
  { code: '+1', country: 'LC', flag: '🇱🇨', label: 'Saint Lucia (+1)' },
  { code: '+508', country: 'PM', flag: '🇵🇲', label: 'Saint Pierre and Miquelon (+508)' },
  { code: '+1', country: 'VC', flag: '🇻🇨', label: 'Saint Vincent and Grenadines (+1)' },
  { code: '+685', country: 'WS', flag: '🇼🇸', label: 'Samoa (+685)' },
  { code: '+378', country: 'SM', flag: '🇸🇲', label: 'San Marino (+378)' },
  { code: '+239', country: 'ST', flag: '🇸🇹', label: 'Sao Tome and Principe (+239)' },
  { code: '+966', country: 'SA', flag: '🇸🇦', label: 'Saudi Arabia (+966)' },
  { code: '+221', country: 'SN', flag: '🇸🇳', label: 'Senegal (+221)' },
  { code: '+381', country: 'RS', flag: '🇷🇸', label: 'Serbia (+381)' },
  { code: '+248', country: 'SC', flag: '🇸🇨', label: 'Seychelles (+248)' },
  { code: '+232', country: 'SL', flag: '🇸🇱', label: 'Sierra Leone (+232)' },
  { code: '+65', country: 'SG', flag: '🇸🇬', label: 'Singapore (+65)' },
  { code: '+421', country: 'SK', flag: '🇸🇰', label: 'Slovakia (+421)' },
  { code: '+386', country: 'SI', flag: '🇸🇮', label: 'Slovenia (+386)' },
  { code: '+677', country: 'SB', flag: '🇸🇧', label: 'Solomon Islands (+677)' },
  { code: '+252', country: 'SO', flag: '🇸🇴', label: 'Somalia (+252)' },
  { code: '+27', country: 'ZA', flag: '🇿🇦', label: 'South Africa (+27)' },
  { code: '+211', country: 'SS', flag: '🇸🇸', label: 'South Sudan (+211)' },
  { code: '+34', country: 'ES', flag: '🇪🇸', label: 'Spain (+34)' },
  { code: '+94', country: 'LK', flag: '🇱🇰', label: 'Sri Lanka (+94)' },
  { code: '+249', country: 'SD', flag: '🇸🇩', label: 'Sudan (+249)' },
  { code: '+597', country: 'SR', flag: '🇸🇷', label: 'Suriname (+597)' },
  { code: '+47', country: 'SJ', flag: '🇸🇯', label: 'Svalbard and Jan Mayen (+47)' },
  { code: '+268', country: 'SZ', flag: '🇸🇿', label: 'Swaziland (+268)' },
  { code: '+46', country: 'SE', flag: '🇸🇪', label: 'Sweden (+46)' },
  { code: '+41', country: 'CH', flag: '🇨🇭', label: 'Switzerland (+41)' },
  { code: '+963', country: 'SY', flag: '🇸🇾', label: 'Syria (+963)' },
  { code: '+886', country: 'TW', flag: '🇹🇼', label: 'Taiwan (+886)' },
  { code: '+992', country: 'TJ', flag: '🇹🇯', label: 'Tajikistan (+992)' },
  { code: '+255', country: 'TZ', flag: '🇹🇿', label: 'Tanzania (+255)' },
  { code: '+66', country: 'TH', flag: '🇹🇭', label: 'Thailand (+66)' },
  { code: '+228', country: 'TG', flag: '🇹🇬', label: 'Togo (+228)' },
  { code: '+690', country: 'TK', flag: '🇹🇰', label: 'Tokelau (+690)' },
  { code: '+676', country: 'TO', flag: '🇹🇴', label: 'Tonga (+676)' },
  { code: '+1', country: 'TT', flag: '🇹🇹', label: 'Trinidad and Tobago (+1)' },
  { code: '+216', country: 'TN', flag: '🇹🇳', label: 'Tunisia (+216)' },
  { code: '+90', country: 'TR', flag: '🇹🇷', label: 'Turkey (+90)' },
  { code: '+993', country: 'TM', flag: '🇹🇲', label: 'Turkmenistan (+993)' },
  { code: '+688', country: 'TV', flag: '🇹🇻', label: 'Tuvalu (+688)' },
  { code: '+256', country: 'UG', flag: '🇺🇬', label: 'Uganda (+256)' },
  { code: '+380', country: 'UA', flag: '🇺🇦', label: 'Ukraine (+380)' },
  { code: '+971', country: 'AE', flag: '🇦🇪', label: 'UAE (+971)' },
  { code: '+44', country: 'GB', flag: '🇬🇧', label: 'United Kingdom (+44)' },
  { code: '+1', country: 'US', flag: '🇺🇸', label: 'United States (+1)' },
  { code: '+1', country: 'VI', flag: '🇻🇮', label: 'US Virgin Islands (+1)' },
  { code: '+598', country: 'UY', flag: '🇺🇾', label: 'Uruguay (+598)' },
  { code: '+998', country: 'UZ', flag: '🇺🇿', label: 'Uzbekistan (+998)' },
  { code: '+678', country: 'VU', flag: '🇻🇺', label: 'Vanuatu (+678)' },
  { code: '+58', country: 'VE', flag: '🇻🇪', label: 'Venezuela (+58)' },
  { code: '+84', country: 'VN', flag: '🇻🇳', label: 'Vietnam (+84)' },
  { code: '+681', country: 'WF', flag: '🇼🇫', label: 'Wallis and Futuna (+681)' },
  { code: '+212', country: 'EH', flag: '🇪🇭', label: 'Western Sahara (+212)' },
  { code: '+967', country: 'YE', flag: '🇾🇪', label: 'Yemen (+967)' },
  { code: '+260', country: 'ZM', flag: '🇿🇲', label: 'Zambia (+260)' },
  { code: '+263', country: 'ZW', flag: '🇿🇼', label: 'Zimbabwe (+263)' },
] as const;

// ─── Availability step options ───

export const WEEKLY_CAPACITY_OPTIONS = [
  { value: 0, label: 'Flexible', description: 'Hours vary per task' },
  { value: 5, label: '~5 hours/week', description: 'Side hustle' },
  { value: 10, label: '~10 hours/week', description: 'Part-time light' },
  { value: 20, label: '~20 hours/week', description: 'Part-time' },
  { value: 30, label: '~30 hours/week', description: 'Near full-time' },
  { value: 40, label: '40+ hours/week', description: 'Full-time' },
];

export const WORK_TYPE_OPTIONS = [
  { value: 'digital', label: 'Digital / Remote', description: 'Online work only' },
  { value: 'physical', label: 'Physical / In-Person', description: 'On-site work' },
  { value: 'both', label: 'Both', description: 'Open to either' },
];
